In [1]:
%matplotlib inline


import matplotlib.pyplot as plt
import matplotlib as matplot
import seaborn as sb
import math
import numpy as np
import pandas as pd
import pydotplus
from scipy import stats
from collections import defaultdict
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from IPython.display import Image

In [2]:
df = pd.read_csv("/Users/matteoppa/Desktop/DataMining/Dataunderstandings.csv")

In [ ]:
df.head()

In [3]:
del (df['Unnamed: 0'])

In [4]:
df['AgeBin'] = pd.cut(df['Age'].astype(int), 10, right=False)

df.drop(['Age'], axis=1, inplace=True)

df.head(100)

,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,Attrition_numerical,AgeBin
0,No,Travel_Rarely,Research & Development,9,4,Medical,2,Male,3,3,...,17,3.0,3,0,2.0,2,8.0,7,0,"[51.6, 55.8)"
1,No,Travel_Rarely,Research & Development,1,1,Life Sciences,2,Male,3,5,...,14,3.0,3,1,3.0,3,1.0,8,0,"[34.8, 39.0)"
2,No,Travel_Frequently,Sales,16,3,Life Sciences,3,Male,3,2,...,25,3.0,3,1,4.0,3,1.0,5,0,"[55.8, 60.042)"
3,No,Travel_Rarely,Research & Development,5,4,Technical Degree,2,Male,3,1,...,14,3.0,2,0,1.0,3,3.0,7,0,"[30.6, 34.8)"
4,No,Travel_Rarely,Research & Development,9,2,Life Sciences,3,Female,3,1,...,12,3.0,3,0,3.0,3,10.0,2,0,"[30.6, 34.8)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,No,Travel_Frequently,Research & Development,8,2,Life Sciences,4,Male,3,1,...,21,3.0,4,0,2.0,3,13.0,3,0,"[34.8, 39.0)"
96,No,Travel_Rarely,Sales,18,1,Life Sciences,1,Male,4,2,...,11,4.0,2,0,3.0,2,5.0,2,0,"[34.8, 39.0)"
97,Yes,Travel_Rarely,Research & Development,2,4,Life Sciences,4,Male,3,5,...,12,3.0,4,0,2.0,3,1.0,15,1,"[34.8, 39.0)"
98,No,Non-Travel,Sales,9,4,Medical,1,Male,3,3,...,13,3.0,4,1,2.0,3,6.0,5,0,"[22.2, 26.4)"
99,No,Travel_Frequently,Sales,5,3,Marketing,4,Female,3,1,...,11,3.0,3,1,2.0,2,9.0,2,0,"[26.4, 30.6)"

In [ ]:
df.head(100)

In [ ]:
df['Attrition'] = df['Attrition'].map(
    {0: 'No', 1: 'Yes'}).astype(str)
df['BusinessTravel'] = df['BusinessTravel'].map(
    {0: 'Non-Travel', 1: 'Travel_Rarely', 2: 'Travel_Frequently'}).astype(str)
df['Department'] = df['Department'].map(
    {0: 'Sales', 1: 'Research & Development', 2: 'Human Resources'}).astype(str)
df['EducationField'] = df['EducationField'].map(
    {0: 'Human Resources', 1: 'Life Sciences', 2: 'Marketing', 3: 'Medical', 4:'Other', 5: 'Technical Degree'}).astype(str)
df['Gender'] = df['Gender'].map(
    {0: 'Female', 1: 'Male'}).astype(str)

df['AgeBin'] = df['AgeBin'].astype(str) + '_Age'


df.head()

In [5]:
del (df['Attrition_numerical'])

In [6]:
baskets = df.values.tolist()

In [7]:
baskets[0]

['No',
 'Travel_Rarely',
 'Research & Development',
 9,
 4,
 'Medical',
 2,
 'Male',
 3,
 3,
 'Research Director',
 3,
 'Single',
 8446.0,
 9,
 'No',
 17,
 3.0,
 3,
 0,
 2.0,
 2,
 8.0,
 7,
 Interval(51.6, 55.8, closed='left')]

In [9]:
from fim import apriori

In [12]:
help(apriori)

Help on built-in function apriori in module fim:

apriori(...)
    apriori (tracts, target='s', supp=10, zmin=1, zmax=None, report='a',
             eval='x', agg='x', thresh=10, prune=None, algo='b', mode='',
             border=None)
    Find frequent item sets with the Apriori algorithm.
    tracts  transaction database to mine (mandatory)
            The database must be an iterable of transactions;
            each transaction must be an iterable of items;
            each item must be a hashable object.
            If the database is a dictionary, the transactions are
            the keys, the values their (integer) multiplicities.
    target  type of frequent item sets to find     (default: s)
            s/a   sets/all   all     frequent item sets
            c     closed     closed  frequent item sets
            m     maximal    maximal frequent item sets
            g     gens       generators
            r     rules      association rules
    supp    minimum support of an item set         (default: 10)
            (positive: percentage, negative: absolute number)
    conf    minimum confidence of an assoc. rule   (default: 80%)
    zmin    minimum number of items per item set   (default: 1)
    zmax    maximum number of items per item set   (default: no limit)
    report  values to report with an item set      (default: a)
            a     absolute item set support (number of transactions)
            s     relative item set support as a fraction
            S     relative item set support as a percentage
            e     value of item set evaluation measure
            E     value of item set evaluation measure as a percentage
            (     combine values in a tuple (must be first character)
            [     combine values in a list  (must be first character)
            #     pattern spectrum as a dictionary  (no patterns)
            =     pattern spectrum as a list        (no patterns)
            |     pattern spectrum as three columns (no patterns)
            for target 'r' (association rules) also available:
            b     absolute body set  support (number of transactions)
            x     relative body set  support as a fraction
            X     relative body set  support as a percentage
            h     absolute head item support (number of transactions)
            y     relative head item support as a fraction
            Y     relative head item support as a percentage
            c     rule confidence as a fraction
            C     rule confidence as a percentage
            l     lift value of a rule (confidence/prior)
            L     lift value of a rule as a percentage
            Q     support of the empty set (total number of transactions)
    eval    measure for item set evaluation        (default: x)
            x     none       no measure / zero (default)
            b     ldratio    binary logarithm of support quotient       (+)
            c     conf       rule confidence                            (+)
            d     confdiff   absolute confidence difference to prior    (+)
            l     lift       lift value (confidence divided by prior)   (+)
            a     liftdiff   absolute difference of lift value to 1     (+)
            q     liftquot   difference of lift quotient to 1           (+)
            v     cvct       conviction (inverse lift negated head)     (+)
            e     cvctdiff   absolute difference of conviction to 1     (+)
            r     cvctquot   difference of conviction quotient to 1     (+)
            k     cprob      conditional probability ratio              (+)
            j     import     importance (binary log. of prob. ratio)    (+)
            z     cert       certainty factor (relative conf. change)   (+)
            n     chi2       normalized chi^2 measure                   (+)
            p     chi2pval   p-value f/ (unnormalized) chi^2 measure    (-)
            y     yates      normalized chi^2 with Yates' correction    (+)
            t     yatespval  p-value f/ Yates-corrected chi^2 measure   (-)
            i     info       information difference to prior            (+)
            g     infopval   p-value f/ G statistic/info. difference    (-)
            f     fetprob    Fisher's exact test (table probability)    (-)
            h     fetchi2    Fisher's exact test (chi^2 measure)        (-)
            m     fetinfo    Fisher's exact test (mutual information)   (-)
            s     fetsupp    Fisher's exact test (support)              (-)
            Measures marked with (+) must meet or exceed the threshold,
            measures marked with (-) must not exceed the threshold
            in order for the item set to be reported.
    agg     evaluation measure aggregation mode    (default: x)
            x     none       no aggregation (use first value)
            m     min        minimum of individual measure values
            n     max        maximum of individual measure values
            a     avg        average of individual measure values
    thresh  threshold for evaluation measure       (default: 10%)
    prune   min. size for evaluation filtering     (default: no pruning)
            = 0   backward filtering       (no subset check)
            < 0   weak   forward filtering (one subset  must qualify)
            > 0   strong forward filtering (all subsets must qualify)
    algo    algorithm variant to use               (default: a)
            b     basic      standard algorithm (only choice)
    mode    operation mode indicators/flags        (default: None)
            x     do not use perfect extension pruning
            t/T   do not organize transactions as a prefix tree
            y     a-posteriori pruning of infrequent item sets
            z     invalidate evaluation below expected support
            o     use original rule support definition (body & head)
    border  support border for filtering item sets (default: None)
            Must be a list or tuple of (absolute) minimum support values
            per item set size (by which the list/tuple is indexed).
    appear  dictionary mapping items to item appearance indicators,
            with the key None referring to the default item appearance.
            (If None does not occur as a key or no dictionary is given,
            the default item appearance indicator is 'both'.)
            This parameter is only used if the target type is rules.
            * item may not appear anywhere in a rule:
              '-', 'n', 'none', 'neither', 'ignore'
            * item may appear only in rule body/antecedent:
              'i', 'in', 'inp', 'input', 'b', 'body',
              'a', 'ante', 'antecedent'
            * item may appear only in rule head/consequent:
              'o', 'out',      'output', 'h', 'head',
              'c', 'cons', 'consequent'
            * item may appear anywhere in a rule:
              'io', 'i&o', 'inout', 'in&out', 'bh', 'b&h', 'both'
    returns if report is not in ['#','=','|']:
              if the target is association rules:
                a list of rules (i.e. tuples with two or more elements),
                each consisting of a head/consequent item, a tuple with
                a body/antecedent item set, and the values selected by
                the parameter 'report', which may be combined into a
                tuple or a list if report[0] is '(' or '[', respectively.
              if the target is a type of item sets:
                a list of patterns (i.e. tuples with one or more elements),
                each consisting of a tuple with a found frequent item set
                and the values selected by the parameter 'report', which
                may be combined into a tuple or list if report[0] is '('
                or '[', respectively
            if report in ['#','=','|']:
              a pattern spectrum as a dictionary mapping pattern sizes
              to the corresponding occurrence support ranges, as a list
              of triplets (size, min. support, max. support) or as three
              columns for sizes and minimum and maximum support values

In [13]:
itemsets = apriori(baskets, supp=10, zmin=5, target='a')

In [14]:
print('Number of itemsets:', len(itemsets))

Number of itemsets: 2806

In [15]:
itemsets[:10]

[((Interval(26.4, 30.6, closed='left'), 4, 'No', 1, 3), 157),
 ((Interval(26.4, 30.6, closed='left'), 4, 'No', 1, 2, 3), 153),
 ((Interval(26.4, 30.6, closed='left'), 4, 'No', 1, 2), 153),
 ((Interval(26.4, 30.6, closed='left'), 4, 'No', 2, 3), 165),
 ((Interval(26.4, 30.6, closed='left'), 4, 1, 2, 3), 172),
 ((Interval(26.4, 30.6, closed='left'), 'No', 1, 2, 3), 176),
 ((12, 4, 'No', 1, 3), 169),
 ((12, 4, 'No', 1, 2, 3), 165),
 ((12, 4, 'No', 1, 2), 165),
 ((12, 4, 'No', 2, 3), 186)]

In [26]:
rules = apriori(baskets, supp=10, zmin=2, target='r', conf=45, 
                report='ascl')

In [25]:
print('Number of rule:', len(rules))

Number of rule: 34703

In [23]:
for r in rules:
    if r[0] == 'Yes':
        print(r)

('Yes', (11, 0, 1, 3), 66, 0.045993031358885016, 0.45517241379310347, 1.2561007957559682)
('Yes', (11, 0, 1), 66, 0.045993031358885016, 0.45517241379310347, 1.2561007957559682)
('Yes', ('Sales', 'Single', 0, 2, 3), 67, 0.046689895470383276, 0.4557823129251701, 1.2577838827838828)
('Yes', ('Sales', 'Single', 0, 2), 67, 0.046689895470383276, 0.4557823129251701, 1.2577838827838828)
('Yes', ('Sales', 'Single', 0, 3), 70, 0.04878048780487805, 0.4605263157894737, 1.2708755060728745)
('Yes', ('Sales', 'Single', 0), 70, 0.04878048780487805, 0.4605263157894737, 1.2708755060728745)
('Yes', ('Sales', 'Single', 2, 3), 67, 0.046689895470383276, 0.4557823129251701, 1.2577838827838828)
('Yes', ('Sales', 'Single', 2), 67, 0.046689895470383276, 0.4557823129251701, 1.2577838827838828)
('Yes', ('Sales', 'Single', 3), 70, 0.04878048780487805, 0.4605263157894737, 1.2708755060728745)
('Yes', ('Sales', 'Single'), 70, 0.04878048780487805, 0.4605263157894737, 1.2708755060728745)

In [21]:
set(rules[0][1])

{3, 15}